name: CD

on:
  # runs at JST0:00 on Sundays
  schedule:
    - cron: "0 15 * * 6"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        env:
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
        run: git clone --depth=1 "https://oauth2:$GL_TOKEN@gitlab.com/isiin/silverblue-nix.git" workspace

      - name: Podman login rootful
        env:
          REG_PASS: ${{ secrets.REG_PASS }}
        run: |
          sudo mkdir -p /root/.config/containers
          echo "$REG_PASS" | sudo podman login --password-stdin \
            --authfile='/root/.config/containers/auth.json' \
            -u isiin quay.io

      - name: Deploy
        run: |
          cd workspace
          sudo ./deploy.sh

